### PR TITLE
Remix V2 version bump

### PR DESCRIPTION
**Pull request by TheRealFlyingCoder**

### CODE REVIEW

**Comment by fedeya** [comment]
needs to update the lockfile (`pnpm-lock.yaml`)

**Comment by TheRealFlyingCoder** [comment]
> needs to update the lockfile (`pnpm-lock.yaml`)

Are you okay to do that? 👀 I was just doing a quick-edit through the browser haha

**Comment by fedeya** [comment]
> > needs to update the lockfile (`pnpm-lock.yaml`)
> 
> 
> 
> Are you okay to do that? 👀 I was just doing a quick-edit through the browser haha
> 
> 

Yes, just use `pnpm install` to generate it.
it is throwing error in the ci build.

**Comment by TheRealFlyingCoder** [comment]
> Yes, just use `pnpm install` to generate it. it is throwing error in the ci build.

Done

**Comment by Olli2** [comment]
Would appreciate this being merged! 🙏

**Pull request merged**
